aws_region = "us-west-2"
db_host = "SETME"
db_port = "SETME"
db_name = "SETME"
db_username = "SETME"
db_password = "SETME"
public_key_path = "/terraform/terraform_key.pub"
private_key_path = "/terraform/terraform_key"